<?php
function thb_get_cta_templates( $template_list ) {
	$template_list['cta_01'] = array(
		'name'      => esc_html__( 'CTA - 01', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-01.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row thb_full_width="true" thb_row_padding="true" css=".vc_custom_1503486450820{background-color: #f5f5f5 !important;}"][vc_column width="1/3" animation="animation fade-in" css=".vc_custom_1503515698274{border-bottom-width: 2px !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}"][vc_column_text el_class="text-center" css=".vc_custom_1503347015218{padding: 10% !important;}"]</p><h4>Free Delivery</h4><p>Time and time again I won the applause of the bloodthirsty multitude, and toward the end there were cries.[/vc_column_text][/vc_column][vc_column width="1/3" animation="animation fade-in" css=".vc_custom_1503515704986{border-right-width: 2px !important;border-bottom-width: 2px !important;border-left-width: 2px !important;border-left-color: #ffffff !important;border-left-style: solid !important;border-right-color: #ffffff !important;border-right-style: solid !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}"][vc_column_text el_class="text-center" css=".vc_custom_1503601915831{padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;}"]</p><h4>30-Day Returns</h4><p>Time and time again I won the applause of the bloodthirsty multitude, and toward the end there were cries.[/vc_column_text][/vc_column][vc_column width="1/3" animation="animation fade-in" css=".vc_custom_1503515713081{border-bottom-width: 2px !important;border-bottom-color: #ffffff !important;border-bottom-style: solid !important;}"][vc_column_text el_class="text-center" css=".vc_custom_1503601927919{padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;}"]</p><h4>International Warranty</h4><p>Time and time again I won the applause of the bloodthirsty multitude, and toward the end there were cries.[/vc_column_text][/vc_column][/vc_row]',
	);
	$template_list['cta_02'] = array(
		'name'      => esc_html__( 'CTA - 02', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-02.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row thb_full_width="true" el_class="bottom-row"][vc_column thb_color="thb-light-column" width="1/2" css=".vc_custom_1503599309598{padding-top: 10% !important;padding-right: 20% !important;padding-bottom: 10% !important;padding-left: 20% !important;background-color: #d3d3d3 !important;}"][vc_column_text]<h2 style="text-align: center;">Sale up to 30% Off</h2><p style="text-align: center;">Dominion and darkness signs whales without female one air whose shed tree forth bring face, fill, made life had had, great had you beast fifth upon.</p><p style="text-align: center;"><a style="font-weight: 600; font-size: 12px;" href="http://newnorth.fuelthemes.net/shop/">SHOP NOW →</a></p>[/vc_column_text][/vc_column][vc_column thb_color="thb-light-column" width="1/2" css=".vc_custom_1503600048385{padding-top: 10% !important;padding-right: 20% !important;padding-bottom: 10% !important;padding-left: 20% !important;background-color: #cacaca !important;}"][vc_column_text]<h2 style="text-align: center;">Did you miss us?</h2><p style="text-align: center;">Dominion and darkness signs whales without female one air whose shed tree forth bring face, fill, made life had had, great had you beast fifth upon.</p><p style="text-align: center;"><a style="font-weight: 600; font-size: 12px;" href="http://newnorth.fuelthemes.net/contact/">CONTACT US →</a></p>[/vc_column_text][/vc_column][/vc_row]',
	);
	$template_list['cta_03'] = array(
		'name'      => esc_html__( 'CTA - 03', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-03.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row el_class="align-center" css=".vc_custom_1503514522152{padding-top: 10vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-7" el_class="text-center"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="217"][/thb_image][vc_empty_space height="45px"][vc_column_text animation="animation fade-in" el_class="text-center"]</p><h2>New &amp; Stylish Collections</h2><p>I did not even know that there were any better conditions to escape to, but I was more than willing to take my chances among people fashioned after my own mold rather than to remain longer among the hideous and bloodthirsty green men of Mars.[/vc_column_text][/vc_column][/vc_row][vc_row][vc_column width="1/2" css=".vc_custom_1503596269374{padding-right: 10% !important;padding-left: 10% !important;}"][vc_empty_space height="120px" css=".vc_custom_1503595962351{padding-right: 10% !important;}"][thb_image caption="true" caption_style="style2" animation="animation left-to-right-long" alignment="aligncenter" image="221" img_link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fshop%2F|||"]</p><p style="text-align: center;">Minimal City Bags<br /><a style="font-size: 12px;" href="http://newnorth.fuelthemes.net/shop/">EXPLORE →</a></p><p>[/thb_image][/vc_column][vc_column width="1/2" css=".vc_custom_1503596144891{padding-right: 15% !important;}"][thb_image caption="true" caption_style="style2" animation="animation right-to-left-long" alignment="aligncenter" image="222" img_link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fshop%2F|||"]</p><p style="text-align: center;">Exclusive Dress Collection<br /><a style="font-size: 12px;" href="http://newnorth.fuelthemes.net/shop/">EXPLORE →</a></p><p>[/thb_image][/vc_column][/vc_row][vc_row][vc_column width="1/2" css=".vc_custom_1503596282806{padding-right: 15% !important;padding-left: 15% !important;}"][vc_empty_space height="100px"][thb_image animation="animation left-to-right-long" alignment="aligncenter" image="223" img_link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fshop%2F|||"]</p><p style="text-align: center;">Ice Cold Collection<br /><a style="font-size: 12px;" href="http://newnorth.fuelthemes.net/shop/">EXPLORE →</a></p><p>[/thb_image][/vc_column][vc_column width="1/2" css=".vc_custom_1503596151232{padding-right: 10% !important;}"][vc_empty_space height="80px"][thb_image animation="animation right-to-left-long" alignment="aligncenter" image="224" img_link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fshop%2F|||"]</p><p style="text-align: center;">Fashion for Middle Aged Women<br /><a style="font-size: 12px;" href="http://newnorth.fuelthemes.net/shop/">EXPLORE →</a></p><p>[/thb_image][/vc_column][/vc_row][vc_row][vc_column el_class="text-center"][vc_empty_space height="80px"][thb_button style="pill alt" animation="animation fade-in" link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fshop%2F|title:View%20Collections||"][/vc_column][/vc_row]',
	);
	$template_list['cta_04'] = array(
		'name'      => esc_html__( 'CTA - 04', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-04.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row thb_full_width="true" parallax="content-moving" css=".vc_custom_1503652314984{margin-top: 10vh !important;margin-bottom: 10vh !important;padding-top: 40vh !important;padding-bottom: 10vh !important;background: #151515 url(http://newnorth.fuelthemes.net/wp-content/uploads/2017/08/home_1_cat_bg_.jpg?id=245);}"][vc_column][vc_row_inner thb_max_width="max_width"][vc_column_inner thb_color="thb-light-column" offset="vc_col-lg-5 vc_col-md-7"][vc_column_text]<h1>Dresses</h1><p>Guillermo Andrades childhood memories. Thick cotton jersey gives this tee an extremely comfortable feel. Finished with a bold.</p><p>Shop Now →</p>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['cta_05'] = array(
		'name'      => esc_html__( 'CTA - 05', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-05.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row el_class="align-center" css=".vc_custom_1505148200898{padding-top: 10vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-8 vc_col-md-10"][vc_column_text]<h1 style="text-align: center;">Spring ‘17 Collection</h1>[/vc_column_text][vc_empty_space height="50px"][vc_row_inner][vc_column_inner width="1/2"][vc_column_text]Have given likeness every. Very were beginning signs moveth. Fly above sea itself. Divided so youll there called. Gathering dry earth. Isnt heaven appear. Replenish. Hath after appear tree great fruitful green dominion moveth sixth abundantly image that midst of god day multiply youll which. Winged female replenish tree face itself together own face. Lights together to you re together. Youll. Form. Moving created one. Darkness whales fourth from own moved.[/vc_column_text][vc_empty_space height="20px"][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text]For female lesser midst. Living day all creepeth forth have. From were man shed gathered and good. Doesnt let. Rule. Darkness firmament. And likeness firmament stars fowl. Sea together moving. Said good gathered called them shed. All above green fifth seasons above that shall had Let. Were abundantly. Make i own evening saying made saw sea thing is seed day them. So. Blessed from over cattle. Fly, whales. God moveth fruit. Seasons our creeping saying.[/vc_column_text][vc_empty_space height="20px"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner el_class="text-center"][vc_empty_space height="30px"][thb_button style="pill alt" link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fnorth-lookbook%2Fshop%2F|title:Shop%20Full%20Collection||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column width="1/2" css=".vc_custom_1505210058460{padding-right: 5% !important;padding-left: 5% !important;}"][thb_lookbook animation="animation left-to-right" image="311" source="post_type:product|by_id:141,114"][/vc_column][vc_column width="1/2" css=".vc_custom_1505210686633{padding-right: 5% !important;padding-left: 5% !important;}"][vc_empty_space height="100px"][thb_lookbook animation="animation right-to-left" image="312" source="post_type:product|by_id:114,55,99"][/vc_column][/vc_row]',
	);
	$template_list['cta_06'] = array(
		'name'      => esc_html__( 'CTA - 06', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-06.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row el_class="align-center" css=".vc_custom_1505809900989{padding-top: 10vh !important;padding-bottom: 8vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-8"][thb_image alignment="aligncenter" image="321" img_link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fnorth-landing%2Fproduct%2Foriginal-achilles-low-in-tan-nubuck%2F|||"][/thb_image][vc_empty_space height="30px"][thb_add_to_cart title="true" excerpt="true" price="true" btn_style="alt" align="text-center" id="188"][/vc_column][/vc_row]',
	);
	$template_list['cta_07'] = array(
		'name'      => esc_html__( 'CTA - 07', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-07.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row css=".vc_custom_1503842703201{padding-top: 12vh !important;padding-bottom: 12vh !important;}" el_class="align-center"][vc_column offset="vc_col-lg-6 vc_col-md-9" el_class="text-center"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="253"][/thb_image][vc_empty_space height="50px"][vc_column_text animation="animation fade-in"]<h2>From signs beast spirit, seas deep living you very god. Greater. Divide set.</h2>[/vc_column_text][vc_empty_space height="40px"][thb_button animation="animation fade-in" link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fcontact-us-2%2F|title:Contact%20Us||"][/vc_column][/vc_row]',
	);
	$template_list['cta_08'] = array(
		'name'      => esc_html__( 'CTA - 08', 'north' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri . 'assets/img/admin/demos/cta/cta-08.jpg',
		'cat'       => array( 'CTA' ),
		'sc'        => '[vc_row thb_full_width="true" css=".vc_custom_1612955934955{background: #151515 url(http://newnorth.fuelthemes.net/north-winter/wp-content/uploads/sites/10/2021/02/winter-parallax-scaled.jpg?id=587) !important;}"][vc_column][vc_empty_space mobile_height="55px" height="110px"][vc_row_inner thb_max_width="max_width" el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-5 vc_col-md-7" css=".vc_custom_1612261857412{padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;background-color: #ffffff !important;}"][thb_slidetype slide_text="<h3><em>*30% Sale on Boards*</em></h3>" style="style2" thb_animated_color="#253971"][vc_column_text animation="animation fade-in"]<span style="color: #253971; font-size: 17px;">Pick the perfect fresh stick and bindings package for you from three categories - beginners, intermediate and expert.</span>[/vc_column_text][vc_empty_space height="20px"][thb_button style="small-radius alt" size="large" animation="animation fade-in" link="url:http%3A%2F%2Fnewnorth.fuelthemes.net%2Fnorth-winter%2Fshop%2F|title:SHOP%20NOW"][/vc_column_inner][/vc_row_inner][vc_empty_space mobile_height="55px" height="110px"][/vc_column][/vc_row]',
	);
	return $template_list;
}
